image:
  - Visual Studio 2015
  - Ubuntu
  - macos

configuration:
  - Debug
  - Release

environment:
  matrix:
    - GENERATOR: MSYS Makefiles
      MSYSTEM: MINGW32
    - GENERATOR: MSYS Makefiles
      MSYSTEM: MINGW64
    - GENERATOR: Unix Makefiles
    - GENERATOR: Visual Studio 14
      VCPKG_TARGET_TRIPLET: x86-windows
    - GENERATOR: Visual Studio 14 Win64
      VCPKG_TARGET_TRIPLET: x64-windows

matrix:
  exclude:
    - image: Ubuntu
      GENERATOR: MSYS Makefiles
      MSYSTEM: MINGW32
    - image: macos
      GENERATOR: MSYS Makefiles
      MSYSTEM: MINGW32
    - image: Ubuntu
      GENERATOR: MSYS Makefiles
      MSYSTEM: MINGW64
    - image: macos
      GENERATOR: MSYS Makefiles
      MSYSTEM: MINGW64
    - image: Ubuntu
      GENERATOR: Visual Studio 14
      VCPKG_TARGET_TRIPLET: x86-windows
    - image: macos
      GENERATOR: Visual Studio 14
      VCPKG_TARGET_TRIPLET: x86-windows
    - image: Ubuntu
      GENERATOR: Visual Studio 14 Win64
      VCPKG_TARGET_TRIPLET: x64-windows
    - image: macos
      GENERATOR: Visual Studio 14 Win64
      VCPKG_TARGET_TRIPLET: x64-windows
    - image: Visual Studio 2015
      GENERATOR: Unix Makefiles
  allow_failures:
    - GENERATOR: MSYS Makefiles

for:
-
  matrix:
    only:
      - GENERATOR: MSYS Makefiles
  install:
    - C:\msys64\usr\bin\bash --login -c "pacman -Su --noconfirm mingw-w64-{i686,x86_64}-{check,libftdi,gperf,libzip,cmake}"
  before_build:
    - C:\msys64\usr\bin\bash --login -c "cd '%APPVEYOR_BUILD_FOLDER%'; mkdir build; cd build; cmake -G'%GENERATOR%' -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS:BOOL=on .."
  build_script:
    - C:\msys64\usr\bin\bash --login -c "cd '%APPVEYOR_BUILD_FOLDER%'; cd build; cmake --build . --verbose --config %CONFIGURATION%"
  test_script:
    - C:\msys64\usr\bin\bash --login -c "cd '%APPVEYOR_BUILD_FOLDER%'; cd build; ctest --output-on-failure"
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update
    - sudo apt-get install -y cmake check gperf libftdi1-dev libzip-dev
  before_build:
    - mkdir build
    - cd build
    - cmake -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DBUILD_SHARED_LIBS:BOOL=on ..
  build_script:
    - cmake --build . --config ${CONFIGURATION} -- VERBOSE=1
  test_script:
    - ctest --output-on-failure
-
  matrix:
    only:
      - image: macos
  install:
    - brew install check libftdi libusb libzip
  before_build:
    - mkdir build
    - cd build
    - cmake -G"${GENERATOR}" -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DBUILD_SHARED_LIBS:BOOL=on -DPKG_CONFIG_EXECUTABLE="/usr/local/bin/pkg-config" ..
  build_script:
    - cmake --build . --config ${CONFIGURATION} -- VERBOSE=1
  test_script:
    - ctest --output-on-failure
  cache:
    - /Users/appveyor/Library/Caches/Homebrew
    - /usr/local/Homebrew

install:
  - cd c:\tools\vcpkg
  - git pull -q
  - git checkout 2020.04
  - vcpkg --triplet %VCPKG_TARGET_TRIPLET% install check gperf libftdi1 libusb libzip[core] getopt-win32
  - cd %APPVEYOR_BUILD_FOLDER%
before_build:
  - mkdir build
  - cd build
  - cmake -G"%GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS:BOOL=on ..
build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package
test_script:
  - ctest --output-on-failure
cache: c:\tools\vcpkg\installed

artifacts:
  - path: 'build/*.zip'
    name: Installer

deploy:
  provider: GitHub
  auth_token:
    secure: vS1tzVAgt5X3XMnX0ioCMmr43MPQdP+im29avhhQOaRZ2BB8QRdtoRdOMmzARBmS
  artifact: Installer
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
    configuration: Release
